### PR TITLE
Add code of conduct, overview

### PR DESCRIPTION
**Pull request by kburk1997**
Addresses issue #44.

Added:
- Community Code of Conduct
- Mentor Code of Conduct
- Introductory Presentation

Notes:
In the presentation, there is a lot of flexibility. Students can agree to the Code of Conduct by including it in their projects and/or filling out the typeform. I can share the typeform with the mentors in case you want to use the typeform response as the attendance code for the first small group meeting. 

I encourage feedback, especially on the mentor Code of Conduct, since it will foster productive discussion on how we as a community can prepare to handle incidents of misconduct as well as use the Code of Conduct to improve RCOS.

### CODE REVIEW

**Comment by kburk1997** [comment]
As per @AdrianCollado's suggestion, the Code of Conduct now allows people to report violations to faculty as well as mentors and coordinators

**Comment by kburk1997** [comment]
I incorporated some of the feedback from the meeting last night and now have a draft of a new Code of Conduct. 

Major changes:

- Directs all incident reporting to faculty, eliminating need for mentor policies on handling incident reports and the potential for conflict with RPI policies
- Adds example guidelines and behaviors, separating them from examples of harassment
- Separates general Code of Conduct to be used on all projects from RPI-specific policies


Draft of Code of Conduct:
# RCOS Community Code of Conduct
In the interest of fostering an open and welcoming environment, RCOS pledges to be an inclusive and harassment-free experience for  all, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, educational background, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation. 

## General
The General Code of Conduct applies to all RCOS and [your project]-affiliated activity online and offline.

### Guidelines
#### Be respectful and inclusive
* **Use inclusive language.**  This includes:
  * using [gender-neutral or non-gendered language](http://geekfeminism.wikia.com/wiki/Nonsexist_language) where possible 
  * when referring to community members, using their preferred pronouns 
  * in general, avoiding any language that could be considered offensive towards marginalized groups
* **Respect people's differences.** Examples include:
  * Being welcoming towards new members
  * Being open to opposing viewpoints
  * Being understanding of cultural differences
  * Making sure your project and any physical spaces your project team may meet are accessible to all members, including members with disabilities

#### Give and be welcoming to constructive feedback
* **Be constructive and respectful** when giving others feedback. This includes:
  * Only giving feedback when solicited (e.g. mock presentation, questions section of presentation, request for code review, pull request, etc.)
  * Keeping all feedback constructive, objective and impersonal  


### Unacceptable Behaviors

Examples of unacceptable behaviors include:

* The use of sexualized language or imagery and unwelcome sexual attention or advances
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others’ private information, such as a physical or electronic address, without explicit permission
* Other conduct which could reasonably be considered inappropriate in a professional setting

### Reporting Incidents

At any point, you may report instances of CoC violations to RCOS faculty at [insert contact info]. You, as well as any other witnesses, have the right to remain anonymous to the rest of the RCOS community.

### Project Maintainer Responsibilities
Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct. In the case of contributors external to RPI and/or RCOS, temporary or permanent bans may occur (RPI-specific policies are outlined [here](insert link to rpi specific stuff)).

## RPI-Specific Policies

This section applies to RCOS meetings at RPI, including large group and small group meetings as well as bonus sessions, casual coding sessions, and any project meetings unless otherwise noted.

### During Large Group
During our large group sessions, we have the following policies.

#### Laptops/Mobile Devices
RCOS likes to maintain a culture of freedom. If you choose to use your laptop or mobile device during large group presentations, you may do so as long as you are mindful of the people around you. This includes:

* muting all audio
* not participating in audio or video calls
* ensuring any material that may be visible on your screen is SFW (safe for work)
* keeping mobile devices on "Silent" or "Vibrate"
* using your device's keyboard instead of a mechanical keyboard

In addition, some speakers may ask audience members to close all laptops and put away all mobile devices. If a speaker does so, please respect their request.

If you absolutely must take a phone call, you can exit the lecture hall to make/take a phone call. If you need to call emergency services for any reason, you may remain in the room while you make the call.

If you use assistive technology due to a documented disability or injury, or you use a medical device that may make noise or looks similar in appearance to a mobile phone or laptop, **please touch base with a faculty member ASAP**. This will remain confidential.

#### Noise
An important part of RCOS is being able to hear from both fellow RCOS members and guest speakers. During presentations, we ask that you refrain from talking or making excessive noise as it can be disruptive to the speaker and to your peers.

### Consequences of Code of Conduct Violations
If you violate the RCOS Community Code of Conduct, appropriate consequences will follow at the discretion of faculty. These may include:

* A verbal or Slack warning from a mentor or coordinator
* A written warning from a faculty member
* A request to edit or delete any blog posts, code, comments, issues, pull requests, milestones, wiki pages, social media posts, etc. that violate the Code of Conduct
* If the violation occurred at an RCOS event or meeting, you may be removed from the event or meeting. This will be marked as an unexcused absence regardless of whether or not you already entered an attendance code, and you will not be able to make up this absence by attending a bonus session.
* In severe and repeated violations, you may be removed from RCOS entirely. If you are taking RCOS for credit, you will receive a failing grade for the semester.

## License and Attribution

This Code of Conduct has been adapted with modifications from the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) and the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). This Code of Conduct, like everything RCOS does, is open source and can be found in our [intro](https://github.com/rcos/intro) repository.

**Comment by Bad-Science** [comment]
Changes look great @kburk1997 ! I think this addresses all of the concerns from yesterday well. Very excited to see this merged in

**Comment by Bad-Science** [comment]
Also 👍  on the inclusive language Respect people's differences sections

**Comment by aeksco** [comment]
:+1: Fantastic work

**Comment by mdznr** [comment]
Is this really necessary? Given that I haven’t been to an RCOS meeting in several years, I wouldn’t know for sure. From the outside, it seems that the program must’ve devolved into students relentlessly harassing their peers to the point where we needed to document what ought to be basic human decency. I feel that if I were to be a prospective RCOS member, I might find such a document an indication that there has historically been serious issues in the community, and a warning that I should avoid such an environment. It’s like when you park your car and spot a large sign:

> Prevent Theft From Your Vehicle
>     * Lock your car every time you leave it unattended.
>     * Take your valuables with you.
>     * Park in a well-lit area.
>     * Be aware of your surroundings.
>     * Report any and all suspicious activity to the police by dialing 911.
> 

Surely such a sign would make anyone pause to question whether they’re personally safe exiting the car, leaving their escape vehicle out of sight. This is not typically a sign of a truly welcoming and flourishing environment.

Upon initially reading the document, the prioritization of certain guidelines seemed questionable. I think the more important guidelines to highlight are those specific to RCOS. RPI’s student handbook might be better suited for many of these guidelines. If the handbook doesn’t already cover these issues, I’d encourage suggesting amendments to the handbook. There, they would have a greater impact to the wider RPI community. I think the document Moorthy shared more succinctly states the expectations of a RCOS member, above the expectations of an RPI student.

----

Although I don’t think the document is necessary, I appreciate its thoroughness. This indicates to me it was written by a strong programmer that’s proactive about guarding against edge cases. I’m excited to learn about all the cool programming projects you all are working on this semester!

**Comment by kburk1997** [comment]
RCOS has now grown to over 150 student developers just at RPI, and we welcome external contributors. Many open source projects, communities, and conferences include Codes of Conduct, and we want to take that step towards building an inclusive community. We haven’t had serious issues in the community yet, but we want to take preventative measures now especially given how toxic “tech bro” culture is to women and how there is a very real danger of RCOS unintentionally adopting “tech bro” culture.

**Comment by kburk1997** [comment]
Here is a link from Open source guide on codes of conduct: https://opensource.guide/code-of-conduct/

In addition, we have been speaking with people from Mozilla about building open source communities and while they were impressed at the size of our organization, they were rather concerned that our organization, and all of our projects, lacked a Code of Conduct.

**Comment by kburk1997** [comment]
You’re right about the RPI handbook covering a lot of these policies, but we are looking to expand our reach beyond RPI and a lot of external contributors will not have access to the RPI handbook, and all of the RPI handbook may not be applicable to RCOS. In addition, the General section can be made into a template for all of our projects to add a Code of Conduct.

**Comment by seveibar** [comment]
Love this, glad to hear that RCOS is continuing to reach outside of RPI, this seems like a good step forward.

The "Unacceptable Behaviors" section seems scary to me, I'm certainly no expert here but I'm not sure if we need to list things that are actually illegal and/or implied by the "Respectful and Inclusive" guidelines i.e. "Public or private harassment", "Unwelcome sexual attention or advances".

However I think the rest of the points are very important and in some cases less obvious, I remember while I was at RPI my phone number, email, name etc. were published to a repo for a demo where I was supposed to be texted via twilio or something. Somebody learned how to rebase that day :)

There's also a couple missing links `[insert contact info]`, ` [here](insert link to rpi specific stuff)`. Other than that great work @kburk1997 👏 👏 👏

**Comment by kburk1997** [comment]
@seveibar The missing links are TBD and will be determined when this PR is merged. Also, the "Unacceptable behaviors" is adapted from the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/), which is used by thousands of open source projects. Especially outside RPI, it's good to have those kinds of behaviors explicitly defined as unacceptable if we ever need to refer to the Code of Conduct.

**Comment by Bad-Science** [comment]
@kburk1997 Amazing job on this. Thanks again for putting so much thought into this, I think it will be a valuable contribution for years to come. Merging now :)

**Pull request merged**
