### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mskmoorthy**
Added the email addresses for the proposal and the slide deck

### CODE REVIEW

**Comment by seveibar** [comment]
@agundy let's make this change for this year-

**Comment by t3dotgg** [comment]
Edit:
If you give me write permission to this repo I can deal with this quickly

**Comment by agundy** [comment]
Just invited you to the team!

**Comment by seveibar** [comment]
@TheoBr any update on this?

**Comment by t3dotgg** [comment]
@seveibar I never got a notification for being invited to the team, can do this first thing today if nobody has yet lol

**Comment by t3dotgg** [comment]
Turns out I'm not a team member still, made a new pull request to deal with this

https://github.com/rcos/intro/pull/15

**Comment by seveibar** [comment]
moved to #15

**Pull request closed without merging**
