### PR TITLE
Update First Two Weeks Agenda

### PR DESCRIPTION
**Pull request by Bad-Science**
Updates first two weeks agenda for Fall 2017 to address issue #28 and #30

### CODE REVIEW

**Review by mskmoorthy — CHANGES_REQUESTED** [review]
It is http://rcos.github.io/intro instead of http://rcos.github.com/intro (Under First Meeting)

Under Second meeting The first paragraph should be moved to First meeting (Didn't we decide that?)

**Comment by Bad-Science** [comment]
@mskmoorthy Do you mean the rubric? I thought we decided that would go in the second meeting. The structure stuff is included in the intro presentation.

I'll change the URL to .io

**Comment by mskmoorthy** [comment]
I thought we had more people giving talks on second day (and our first day was nearly empty - unless we are going to help students get into slack and set a github account). But I am okay with either first or second meeting

**Comment by Bad-Science** [comment]
Yes the second day will be mostly talks but we also need to explain the rubric - and I don't want to scare people of by talking about grades the first day

**Comment by mskmoorthy** [comment]
OK. Once you make change to the url I can merge

**Review by mskmoorthy — APPROVED** [review]

**Pull request merged**
